# --- BC specific parameters ---

# use multinomial selector
action_selector: "multinomial"
epsilon_start: .5
epsilon_finish: .05
epsilon_anneal_time: 500000

runner: "parallel"

buffer_size: 32
off_buffer_size: 70000 # size of the off-policy buffer default: 5000
batch_size_run: 10 # 10 num of parellel envs
batch_size: 16
off_batch_size: 32  # batch_size_train

env_args:
  state_last_action: True # critic adds last action internally

# use the BC_Learner to train
agent_output_type: "pi_logits"
learner: "bc_learner"
lr: 0.0005
mask_before_softmax: False

name: "BC"

offline_dataset_dir: "/data/user/kouqian/files/MAOfflineDatasets/SMAC410_pref_new/5m_vs_6m_good-medium_1000_30.th"
offline_dataset_quality: "good-medium"
pref_segment_pairs: 1000
use_pref: False