# --- COMA specific parameters ---

action_selector: "multinomial"
epsilon_start: .5
epsilon_finish: .05
epsilon_anneal_time: 500000
mask_before_softmax: False

runner: "parallel"

buffer_size: 32
off_buffer_size: 70000 # size of the off-policy buffer default: 5000
batch_size_run: 10 # 10 num of parellel envs
batch_size: 16
off_batch_size: 32  # batch_size_train

env_args:
  state_last_action: True # critic adds last action internally


lr: 0.0005
dpo_lambda: 0.1
dpo_alpha: 1000

distence_type: "log_pi"  # "pi", "log_pi", "actions"
distence_log: True

agent_mixer: "attention"  # "none", "attention"
time_mixer: "attention"  # "none"

# qatten mixer
n_query_embedding_layer1: 64
n_query_embedding_layer2: 32
n_key_embedding_layer1: 32
n_head_embedding_layer1: 64
n_head_embedding_layer2: 4
n_attention_head: 4
n_constant_value: 32
qatten_type: "weighted"  # "none"
traj_feature_rtgs: 4

# use qmix
mixing_embed_dim: 32

# use COMA
agent_output_type: "pi_logits"  # "q"
learner: "madpo_learner"
q_nstep: 0  # 0 corresponds to default Q, 1 is r + gamma*Q, etc

name: "MADPO"

offline_dataset_dir: "/data/user/kouqian/files/MAOfflineDatasets/SMAC410_pref_new/5m_vs_6m_good-medium_1000_30.th"
offline_dataset_quality: "good-medium"
pref_segment_pairs: 1000
use_pref: True

train_reward: False
max_traj_length: 30
model_type: "MR"
action_type: "Discrete"
reward_train_epoch: 100
reward_batch_size: 128
use_reward_hat: False