# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.99
epsilon_anneal_time: 10000

runner: "episode"

buffer_size: 100
batch_size: 1

# spec for overcooked, cause obs contains other agent's infos
obs_agent_id: False
obs_last_action: False
obs_individual_obs: False

# update the target network every {} episodes
# target_update_interval_or_tau
# or soft update tau
target_update_interval_or_tau: 0.01 

# maddpg stuff
agent: "mlp_ns"
mac: "maddpg_mac"
critic_type: "maddpg_critic_ns"
learner: "maddpg"
agent_output_type: "pi_logits" 
use_rnn: False
reg: 0.001
central_loss: 1
qmix_loss: 1
hidden_dim: 64
lr: 0.0001 # Learning rate for agents
critic_lr: 0.001 # Learning rate for critics
grad_norm_clip: 0.5
gamma: 0.95

name: "maddpg_ns"