env: overcooked

env_args:
  map_name: "cramped_room"
  horizon: 200
  shape_reward: True
  vision_obs: False

test_greedy: True
test_nepisode: 16
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 500000
