env: overcooked

env_args:
  map_name: "asymmetric_advantages"
  horizon: 500
  shape_reward: True
  vision_obs: False

test_greedy: True
test_nepisode: 3
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 1050000
